services:

  postgres:
    image: postgres:16-alpine
    container_name: curso_springboot_db

    environment:
      POSTGRES_DB: curso_springboot
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d curso_springboot"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .

    ports:
      - "8080:8080"
      - "8081:8081"

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JPA_DDL: ${JPA_DDL}

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: