# ===================================
# CONFIGURACIÓN DEL SERVIDOR
# ===================================

server.port=8080

# ===================================
# CONFIGURACIÓN BASE DE DATOS (PostgreSQL)
# ===================================

# Docker Compose:
# usa DB_URL=jdbc:postgresql://postgres:5432/curso_springboot
#
# IntelliJ/local:
# usa el valor por defecto localhost:5432

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/curso_springboot}
spring.datasource.username=${DB_USERNAME:devdb}
spring.datasource.password=${DB_PASSWORD:a1b2c3d4}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================
# CONFIGURACIÓN HIKARICP (POOL DE CONEXIONES)
# ===================================

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=HikariPool-Clientes

# ===================================
# CONFIGURACIÓN JPA / HIBERNATE
# ===================================

spring.jpa.hibernate.ddl-auto=${JPA_DDL:create-drop}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================
# ACTUATOR (MONITOREO)
# ===================================

management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator

management.server.port=8081
management.endpoint.health.show-details=always

# ===================================
# LOGGING (VER SQL EN CONSOLA)
# ===================================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===================================
# CONFIGURACIÓN MULTIPART (ARCHIVOS)
# ===================================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB